app/src/main/java/com/expidev/gcmapp/MainActivity.java
=> fix memory leak

app/src/main/java/com/expidev/gcmapp/MainActivity.java
=> fix memory leak V2

app/src/main/AndroidManifest.xml, app/src/main/java/com/expidev/gcmapp/GcmTheKey/GcmBroadcastReceiver.java, app/src/main/java/com/expidev/gcmapp/GcmTheKey/GcmTheKeyHelper.java, app/src/main/java/com/expidev/gcmapp/MainActivity.java, app/src/main/java/com/expidev/gcmapp/Sync/ConnectionBroadcastReceiver.java, app/src/main/java/com/expidev/gcmapp/http/GcmApiClient.java, app/src/main/java/com/expidev/gcmapp/http/TicketTask.java, app/src/main/java/com/expidev/gcmapp/http/TokenTask.java, app/src/main/res/layout/activity_main.xml
- fetch/generate service url for GCM api
- retrieve a service ticket for the service url: String ticket = theKey.getTicket(serviceUrl)
- use service ticket to authenticate to GCM api, which returns a GCM session token
- use GCM session token to make api calls
=> Correct the way connection to the api is made

app/src/main/AndroidManifest.xml, app/src/main/java/com/expidev/gcmapp/MainActivity.java, app/src/main/java/com/expidev/gcmapp/MapSettings.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/pref_map.xml
@wrandall22 here are the settings. I should have included this with my last PR.
=> Map settings

app/src/main/java/com/expidev/gcmapp/MainActivity.java, app/src/main/java/com/expidev/gcmapp/db/Contract.java, app/src/main/java/com/expidev/gcmapp/utils/DatabaseOpenHelper.java
I'm going to convert some of the UI data loading to utilize Content Loaders
=> Content Loaders

app/build.gradle, app/src/androidTest/java/com/expidev/gcmapp/db/MinistriesDaoTest.java, app/src/main/java/com/expidev/gcmapp/JoinMinistryActivity.java, app/src/main/java/com/expidev/gcmapp/MainActivity.java, app/src/main/java/com/expidev/gcmapp/db/MinistriesDao.java, app/src/main/java/com/expidev/gcmapp/http/GmaApiClient.java, app/src/main/java/com/expidev/gcmapp/json/AssignmentsJsonParser.java, app/src/main/java/com/expidev/gcmapp/model/Assignment.java, app/src/main/java/com/expidev/gcmapp/service/AuthService.java, app/src/main/java/com/expidev/gcmapp/service/MeasurementsService.java, app/src/main/java/com/expidev/gcmapp/service/MinistriesService.java, app/src/main/java/com/expidev/gcmapp/service/TrainingService.java
This branch utilizes a common API client framework that tries to abstract some of the repetitive raw connection tasks and session management away from the API being implemented.
=> API session management

app/src/main/java/com/expidev/gcmapp/MeasurementDetailsActivity.java, app/src/main/java/com/expidev/gcmapp/MeasurementsActivity.java, app/src/main/java/com/expidev/gcmapp/service/MeasurementsService.java, app/src/main/res/layout/base_graph.xml, app/src/main/res/values/strings.xml
This branch fixes several little bugs dealing with measurements and measurement details.
=> Fix measurement details

app/src/androidTest/java/com/expidev/gcmapp/db/MinistriesDaoTest.java, app/src/main/java/com/expidev/gcmapp/JoinMinistryActivity.java, app/src/main/java/com/expidev/gcmapp/db/AssignmentMapper.java, app/src/main/java/com/expidev/gcmapp/db/Contract.java, app/src/main/java/com/expidev/gcmapp/db/MinistriesDao.java, app/src/main/java/com/expidev/gcmapp/json/AssignmentsJsonParser.java, app/src/main/java/com/expidev/gcmapp/model/Assignment.java, app/src/main/java/com/expidev/gcmapp/sql/TableNames.java, app/src/main/java/com/expidev/gcmapp/tasks/CreateAssignmentTask.java, app/src/main/java/com/expidev/gcmapp/utils/DatabaseOpenHelper.java
This PR will issue the createAssignment API request to the backend and handle the response. It is based off PR #25 and should be reviewed/merged after that one
=> Actually create new assignments

app/src/main/java/com/expidev/gcmapp/MainActivity.java, app/src/main/java/com/expidev/gcmapp/SettingsActivity.java, app/src/main/java/com/expidev/gcmapp/db/MinistriesDao.java
This PR fixes some default values issues
=> Mcc and ministry defaults

app/src/androidTest/java/com/expidev/gcmapp/json/TrainingJsonParserTest.java, app/src/main/java/com/expidev/gcmapp/db/TrainingDao.java, app/src/main/java/com/expidev/gcmapp/json/TrainingJsonParser.java, app/src/main/java/com/expidev/gcmapp/model/Training.java
@frett @wrandall22 I created a test to for the training JSON parser and the training Dao and the test is not working. I was hoping you guys might see the problem. I parse in a JSON array which creates 2 training objects. I then save them, and retrieve them. When I retrieve them I only get one back. It seems like the Dao is updating when it should be inserting.
=> Fix training loading

app/src/main/java/com/expidev/gcmapp/http/GmaApiClient.java, app/src/main/java/com/expidev/gcmapp/model/Training.java, app/src/main/java/com/expidev/gcmapp/service/MinistriesService.java, app/src/main/java/com/expidev/gcmapp/service/TrainingService.java
@frett This should take care of the training sync
=> sync dirty

app/src/main/java/com/expidev/gcmapp/MainActivity.java
this data is now managed by the TrainingLoader
=> remove unnecessary BroadcastReceivers

app/src/main/java/com/expidev/gcmapp/Constants.java, app/src/main/java/com/expidev/gcmapp/MainActivity.java, app/src/main/java/com/expidev/gcmapp/MeasurementDetailsActivity.java, app/src/main/java/com/expidev/gcmapp/MeasurementsActivity.java, app/src/main/java/com/expidev/gcmapp/db/Contract.java, app/src/main/java/com/expidev/gcmapp/service/MeasurementsService.java, app/src/main/java/com/expidev/gcmapp/support/v4/content/CurrentAssignmentLoader.java, app/src/main/java/com/expidev/gcmapp/utils/DatabaseOpenHelper.java
This PR should be able to close out #43
=> Sync measurements

app/src/main/java/com/expidev/gcmapp/MeasurementsActivity.java, app/src/main/java/com/expidev/gcmapp/db/Contract.java, app/src/main/java/com/expidev/gcmapp/db/MeasurementMapper.java, app/src/main/java/com/expidev/gcmapp/json/MeasurementsJsonParser.java, app/src/main/java/com/expidev/gcmapp/model/measurement/Measurement.java, app/src/main/java/com/expidev/gcmapp/utils/DatabaseOpenHelper.java
Sorts measurements using Sort_Order from server.  Based on #50
=> Sort measurements

app/src/main/java/com/expidev/gcmapp/MeasurementsActivity.java
This does not save anything to the server, only to the local database
=> Enable self assigned users to save measurements to local database

app/src/main/java/com/expidev/gcmapp/support/v4/fragment/SettingsFragment.java, app/src/main/res/values/strings_activity_settings.xml, app/src/main/res/xml/pref_general.xml
=> display more informative message for the active ministry preference

app/src/main/java/com/expidev/gcmapp/db/Contract.java, app/src/main/java/com/expidev/gcmapp/support/v4/content/MinistriesCursorLoader.java, app/src/main/java/com/expidev/gcmapp/support/v4/fragment/SettingsFragment.java
* filter list of AssociatedMinistrys based on current assignments
=> add Join support between AssociatedMinistry and Assignment

app/src/main/java/com/expidev/gcmapp/db/Contract.java, app/src/main/java/com/expidev/gcmapp/db/MinistryMapper.java, app/src/main/java/com/expidev/gcmapp/model/Ministry.java, app/src/main/java/com/expidev/gcmapp/service/MinistriesService.java, app/src/main/java/com/expidev/gcmapp/utils/DatabaseOpenHelper.java
=> Mccs JSON parsing

app/src/main/java/com/expidev/gcmapp/http/GmaApiClient.java
MMAND-12:  Removed the onPrepareUri and added code to the
onPrepareRequest to pass in Bearer Token.
=> [MMAND-12]

app/src/main/java/com/expidev/gcmapp/MeasurementDetailsActivity.java, app/src/main/res/layout/base_graph.xml
Changed formatting on the measurements map screen to coincide with the
color palette of the new brand.
=> [MMAND-16]
